spring.application.name=movie-explorer-api

# Run the backend on port 8080
server.port=8080

# Neo4j Database Connection (Reading from Environment Variables)
neo4j.uri=${COGNO_DB_URI}
neo4j.username=${COGNO_DB_USER}
neo4j.password=${COGNO_DB_PASSWORD}